import asyncio
import pyautogui
from typing import Literal, Optional
from livekit.agents import function_tool

# Configure pyautogui safety settings
pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.1

@function_tool()
async def keyboard_macros(shortcut: Literal["settings", "task_view", "action_center", "lock_pc", "custom"], custom_keys: Optional[str] = None) -> str:
    """
    Executes advanced keyboard shortcut combinations and macros for system automation.
    
    Args:
        shortcut: Shortcut macro to run:
            - "settings": Opens Windows Settings (Win + I)
            - "task_view": Launches Task View (Win + Tab)
            - "action_center": Opens Windows Notification Action Center (Win + A)
            - "display_settings": Opens Display Settings (Win + P)
            - "show_run": Opens Run Dialog (Win + R)
            - "show_file_explorer": Opens File Explorer (Win + E)
            - "switch_monitor": Switch displays (Ctrl + Win + Arrow keys)
            - "task_manager": Opens Task Manager (Ctrl + Shift + Esc)
            - "show_desktop": Shows desktop (Win + D)
            - "show_search": Shows search bar (Win + S)
            - "show_chat": Shows Cortana/Search (Win + Q)
            - "show_camera": Opens Camera app (Win + C)
            - "open_notepad": Opens Notepad (Ctrl + N)
            - "open_word": Opens Word (Ctrl + Alt + W)
            - "open_excel": Opens Excel (Ctrl + Alt + E)
            - "open_powerpoint": Opens PowerPoint (Ctrl + Alt + P)
            - "open_outlook": Opens Outlook (Ctrl + Alt + O)
            - "open_paint": Opens Paint (Ctrl + Alt + P)
            - "open_wordpad": Opens WordPad (Ctrl + Alt + W)
            - "open_calculator": Opens Calculator (Ctrl + Alt + C)
            - "open_cmd": Opens Command Prompt (Ctrl + Alt + C)
            - "open_powershell": Opens PowerShell (Ctrl + Alt + P)
            - "open_msedge": Opens Microsoft Edge (Ctrl + Alt + M)
            - "open_calendar": Opens Calendar (Win + Alt + D)
            - "open_camera": Opens Camera (Win + Alt + C)
            - "open_clock": Opens Clock app (Win + Alt + A)
            - "open_calculator": Opens Calculator (Win + Alt + C)
            - "open_feedback": Opens Feedback Hub (Win + Alt + B)
            - "open_store": Opens Microsoft Store (Win + Alt + E)
            - "open_sticky_notes": Opens Sticky Notes (Win + Alt + S)
            - "open_wallet": Opens Wallet (Win + Alt + W)
            - "open_calculator": Opens Calculator (Win + Alt + C)
            - "open_file_explorer": Opens File Explorer (Win + Alt + E)
            - "open_mail": Opens Mail app (Win + Alt + M)
            - "open_messenger": Opens Messenger (Win + Alt + N)
            - "open_network": Opens Network Settings (Win + Alt + N)
            - "open_print3d": Opens Print3D app (Win + Alt + P)
            - "open_one_note": Opens OneNote (Win + Alt + O)
            - "open_photos": Opens Photos app (Win + Alt + P)
            - "open_maps": Opens Maps app (Win + Alt + M)
            - "open_mixed_reality": Opens Mixed Reality Portal (Win + Alt + M)
            - "open_recorder": Opens Recorder app (Win + Alt + R)
            - "open_groove": Opens Groove Music (Win + Alt + G)
            - "open_movies_tv": Opens Movies & TV (Win + Alt + M)
            - "open_xbox": Opens Xbox app (Win + Alt + X)
            - "open_grip": Opens Grip app (Win + Alt + G)
            - "open_xbox_gamebar": Opens Xbox Game Bar (Win + Alt + G)
            - "open_cortana": Opens Cortana (Win + Alt + C)
            - "open_cortana_search": Opens Cortana Search (Win + Alt + C)
            - "open_windows_security": Opens Windows Security (Win + Alt + S)
            - "open_snipping_tool": Opens Snipping Tool (Win + Alt + S)
            - "open_voice_recorder": Opens Voice Recorder (Win + Alt + R)
            - "open_whatsapp": Opens WhatsApp (Win + Alt + W)
            - "open_telegram": Opens Telegram (Win + Alt + T)
            - "open_messenger": Opens Messenger (Win + Alt + M)
            - "open_instagram": Opens Instagram (Win + Alt + I)
            - "open_facebook": Opens Facebook (Win + Alt + F)
            - "open_twitter": Opens Twitter (Win + Alt + T)
            - "open_linkedin": Opens LinkedIn (Win + Alt + L)
            - "open_whatsapp_web": Opens WhatsApp Web (Win + Alt + W)
            - "open_telegram_web": Opens Telegram Web (Win + Alt + T)
            - "open_messenger_web": Opens Messenger Web (Win + Alt + M)
            - "open_instagram_web": Opens Instagram Web (Win + Alt + I)
            - "open_facebook_web": Opens Facebook Web (Win + Alt + F)
            - "open_twitter_web": Opens Twitter Web (Win + Alt + T)
            - "open_linkedin_web": Opens LinkedIn Web (Win + Alt + L)
            - "open_whatsapp_desktop": Opens WhatsApp Desktop (Win + Alt + W)
            - "open_telegram_desktop": Opens Telegram Desktop (Win + Alt + T)
            - "open_messenger_desktop": Opens Messenger Desktop (Win + Alt + M)
            - "open_instagram_desktop": Opens Instagram Desktop (Win + Alt + I)
            - "open_facebook_desktop": Opens Facebook Desktop (Win + Alt + F)
            - "open_twitter_desktop": Opens Twitter Desktop (Win + Alt + T)
            - "open_linkedin_desktop": Opens LinkedIn Desktop (Win + Alt + L)
            - "open_chrome": Opens Google Chrome (Win + Alt + C)
            - "open_edge": Opens Microsoft Edge (Win + Alt + E)
            - "open_firefox": Opens Mozilla Firefox (Win + Alt + F)
            - "open_brave": Opens Brave Browser (Win + Alt + B)
            - "open_opera": Opens Opera Browser (Win + Alt + O)
            - "open_opera_gx": Opens Opera GX Browser (Win + Alt + G)
            - "open_chrome_incognito": Opens Chrome Incognito Mode (Win + Alt + I)
            - "open_edge_incognito": Opens Edge Incognito Mode (Win + Alt + I)
            - "open_firefox_private": Opens Firefox Private Browsing (Win + Alt + P)
            - "open_brave_private": Opens Brave Private Browsing (Win + Alt + P)
            - "open_opera_private": Opens Opera Private Browsing (Win + Alt + P)
            - "open_chrome_guest": Opens Chrome Guest Mode (Win + Alt + G)
            - "open_edge_guest": Opens Edge Guest Mode (Win + Alt + G)
            - "open_firefox_guest": Opens Firefox Guest Mode (Win + Alt + G)
            - "open_brave_guest": Opens Brave Guest Mode (Win + Alt + G)
            - "open_opera_guest": Opens Opera Guest Mode (Win + Alt + G)
            - "open_chrome_dev_tools": Opens Chrome Developer Tools (Win + Alt + D)
            - "open_edge_dev_tools": Opens Edge Developer Tools (Win + Alt + D)
            - "open_firefox_dev_tools": Opens Firefox Developer Tools (Win + Alt + D)
            - "open_brave_dev_tools": Opens Brave Developer Tools (Win + Alt + D)
            - "open_opera_dev_tools": Opens Opera Developer Tools (Win + Alt + D)
            - "open_chrome_bookmarks": Opens Chrome Bookmarks (Win + Alt + B)
            - "open_edge_bookmarks": Opens Edge Bookmarks (Win + Alt + B)
            - "open_firefox_bookmarks": Opens Firefox Bookmarks (Win + Alt + B)
            - "open_brave_bookmarks": Opens Brave Bookmarks (Win + Alt + B)
            - "open_opera_bookmarks": Opens Opera Bookmarks (Win + Alt + B)
            - "open_chrome_history": Opens Chrome History (Win + Alt + H)
            - "open_edge_history": Opens Edge History (Win + Alt + H)
            - "open_firefox_history": Opens Firefox History (Win + Alt + H)
            - "open_brave_history": Opens Brave History (Win + Alt + H)
            - "open_opera_history": Opens Opera History (Win + Alt + H)
            - "open_chrome_downloads": Opens Chrome Downloads (Win + Alt + D)
            - "open_edge_downloads": Opens Edge Downloads (Win + Alt + D)
            - "open_firefox_downloads": Opens Firefox Downloads (Win + Alt + D)
            - "open_brave_downloads": Opens Brave Downloads (Win + Alt + D)
            - "open_opera_downloads": Opens Opera Downloads (Win + Alt + D)
            - "open_chrome_settings": Opens Chrome Settings (Win + Alt + S)
            - "open_edge_settings": Opens Edge Settings (Win + Alt + S)
            - "open_firefox_settings": Opens Firefox Settings (Win + Alt + S)
            - "open_brave_settings": Opens Brave Settings (Win + Alt + S)
            - "open_opera_settings": Opens Opera Settings (Win + Alt + S)
            - "open_chrome_new_tab": Opens Chrome New Tab (Win + Alt + T)
            - "open_edge_new_tab": Opens Edge New Tab (Win + Alt + T)
            - "open_firefox_new_tab": Opens Firefox New Tab (Win + Alt + T)
            - "open_brave_new_tab": Opens Brave New Tab (Win + Alt + T)
            - "open_opera_new_tab": Opens Opera New Tab (Win + Alt + T)
            - "open_chrome_close_tab": Opens Chrome Close Tab (Win + Alt + C)
            - "open_edge_close_tab": Opens Edge Close Tab (Win + Alt + C)
            - "open_firefox_close_tab": Opens Firefox Close Tab (Win + Alt + C)
            - "open_brave_close_tab": Opens Brave Close Tab (Win + Alt + C)
            - "open_opera_close_tab": Opens Opera Close Tab (Win + Alt + C)
            - "open_chrome_reopen_tab": Opens Chrome Reopen Tab (Win + Alt + R)
            - "open_edge_reopen_tab": Opens Edge Reopen Tab (Win + Alt + R)
            - "open_firefox_reopen_tab": Opens Firefox Reopen Tab (Win + Alt + R)
            - "open_brave_reopen_tab": Opens Brave Reopen Tab (Win + Alt + R)
            - "open_opera_reopen_tab": Opens Opera Reopen Tab (Win + Alt + R)
            - "open_chrome_next_tab": Opens Chrome Next Tab (Win + Alt + N)
            - "open_edge_next_tab": Opens Edge Next Tab (Win + Alt + N)
            - "open_firefox_next_tab": Opens Firefox Next Tab (Win + Alt + N)
            - "open_brave_next_tab": Opens Brave Next Tab (Win + Alt + N)
            - "open_opera_next_tab": Opens Opera Next Tab (Win + Alt + N)
            - "open_chrome_previous_tab": Opens Chrome Previous Tab (Win + Alt + P)
            - "open_edge_previous_tab": Opens Edge Previous Tab (Win + Alt + P)
            - "open_firefox_previous_tab": Opens Firefox Previous Tab (Win + Alt + P)
            - "open_brave_previous_tab": Opens Brave Previous Tab (Win + Alt + P)
            - "open_opera_previous_tab": Opens Opera Previous Tab (Win + Alt + P)
            - "open_chrome_close_other_tabs": Opens Chrome Close Other Tabs (Win + Alt + O)
            - "open_edge_close_other_tabs": Opens Edge Close Other Tabs (Win + Alt + O)
            - "open_firefox_close_other_tabs": Opens Firefox Close Other Tabs (Win + Alt + O)
            - "open_brave_close_other_tabs": Opens Brave Close Other Tabs (Win + Alt + O)
            - "open_opera_close_other_tabs": Opens Opera Close Other Tabs (Win + Alt + O)
            - "open_chrome_close_tabs_to_the_right": Opens Chrome Close Tabs to the Right (Win + Alt + T)
            - "open_edge_close_tabs_to_the_right": Opens Edge Close Tabs to the Right (Win + Alt + T)
            - "open_firefox_close_tabs_to_the_right": Opens Firefox Close Tabs to the Right (Win + Alt + T)
            - "open_brave_close_tabs_to_the_right": Opens Brave Close Tabs to the Right (Win + Alt + T)
            - "open_opera_close_tabs_to_the_right": Opens Opera Close Tabs to the Right (Win + Alt + T)
            - "open_chrome_reopen_closed_tab": Opens Chrome Reopen Closed Tab (Win + Alt + R)
            - "open_edge_reopen_closed_tab": Opens Edge Reopen Closed Tab (Win + Alt + R)
            - "open_firefox_reopen_closed_tab": Opens Firefox Reopen Closed Tab (Win + Alt + R)
            - "open_brave_reopen_closed_tab": Opens Brave Reopen Closed Tab (Win + Alt + R)
            - "open_opera_reopen_closed_tab": Opens Opera Reopen Closed Tab (Win + Alt + R)
            - "open_chrome_reopen_all_tabs": Opens Chrome Reopen All Tabs (Win + Alt + A)
            - "open_edge_reopen_all_tabs": Opens Edge Reopen All Tabs (Win + Alt + A)
            - "open_firefox_reopen_all_tabs": Opens Firefox Reopen All Tabs (Win + Alt + A)
            - "open_brave_reopen_all_tabs": Opens Brave Reopen All Tabs (Win + Alt + A)
            - "open_opera_reopen_all_tabs": Opens Opera Reopen All Tabs (Win + Alt + A)
            - "open_chrome_new_window": Opens Chrome New Window (Win + Alt + N)
            - "open_edge_new_window": Opens Edge New Window (Win + Alt + N)
            - "open_firefox_new_window": Opens Firefox New Window (Win + Alt + N)
            - "open_brave_new_window": Opens Brave New Window (Win + Alt + N)
            - "open_opera_new_window": Opens Opera New Window (Win + Alt + N)
            - "open_chrome_new_incognito_window": Opens Chrome New Incognito Window (Win + Alt + I)
            - "open_edge_new_incognito_window": Opens Edge New Incognito Window (Win + Alt + I)
            - "open_firefox_new_private_window": Opens Firefox New Private Window (Win + Alt + P)
            - "open_brave_new_private_window": Opens Brave New Private Window (Win + Alt + P)
            - "open_opera_new_private_window": Opens Opera New Private Window (Win + Alt + P)
            - "open_chrome_new_guest_window": Opens Chrome New Guest Window (Win + Alt + G)
            - "open_edge_new_guest_window": Opens Edge New Guest Window (Win + Alt + G)
            - "open_firefox_new_guest_window": Opens Firefox New Guest Window (Win + Alt + G)
            - "open_brave_new_guest_window": Opens Brave New Guest Window (Win + Alt + G)
            - "open_opera_new_guest_window": Opens Opera New Guest Window (Win + Alt + G)
            - "open_chrome_new_window_from_bookmarks": Opens Chrome New Window from Bookmarks (Win + Alt + B)
            - "open_edge_new_window_from_bookmarks": Opens Edge New Window from Bookmarks (Win + Alt + B)
            - "open_firefox_new_window_from_bookmarks": Opens Firefox New Window from Bookmarks (Win + Alt + B)
            - "open_brave_new_window_from_bookmarks": Opens Brave New Window from Bookmarks (Win + Alt + B)
            - "open_opera_new_window_from_bookmarks": Opens Opera New Window from Bookmarks (Win + Alt + B)
            - "open_chrome_new_window_from_history": Opens Chrome New Window from History (Win + Alt + H)
            - "open_edge_new_window_from_history": Opens Edge New Window from History (Win + Alt + H)
            - "open_firefox_new_window_from_history": Opens Firefox New Window from History (Win + Alt + H)
            - "open_brave_new_window_from_history": Opens Brave New Window from History (Win + Alt + H)
            - "open_opera_new_window_from_history": Opens Opera New Window from History (Win + Alt + H)
            - "open_chrome_new_window_from_downloads": Opens Chrome New Window from Downloads (Win + Alt + D)
            - "open_edge_new_window_from_downloads": Opens Edge New Window from Downloads (Win + Alt + D)
            - "open_firefox_new_window_from_downloads": Opens Firefox New Window from Downloads (Win + Alt + D)
            - "open_brave_new_window_from_downloads": Opens Brave New Window from Downloads (Win + Alt + D)
            - "open_opera_new_window_from_downloads": Opens Opera New Window from Downloads (Win + Alt + D)
            - "open_chrome_new_window_from_settings": Opens Chrome New Window from Settings (Win + Alt + S)
            - "open_edge_new_window_from_settings": Opens Edge New Window from Settings (Win + Alt + S)
            - "open_firefox_new_window_from_settings": Opens Firefox New Window from Settings (Win + Alt + S)
            - "open_brave_new_window_from_settings": Opens Brave New Window from Settings (Win + Alt + S)
            - "open_opera_new_window_from_settings": Opens Opera New Window from Settings (Win + Alt + S)
            - "open_chrome_new_window_from_developer_tools": Opens Chrome New Window from Developer Tools (Win + Alt + D)
            - "open_edge_new_window_from_developer_tools": Opens Edge New Window from Developer Tools (Win + Alt + D)
            - "open_firefox_new_window_from_developer_tools": Opens Firefox New Window from Developer Tools (Win + Alt + D)
            - "open_brave_new_window_from_developer_tools": Opens Brave New Window from Developer Tools (Win + Alt + D)
            - "open_opera_new_window_from_developer_tools": Opens Opera New Window from Developer Tools (Win + Alt + D)
            - "settings": Opens Windows Settings (Win + I)
            lock_pc": Locks PC screen safely
            - "custom": Custom key combination (e.g., "alt,f4" or "ctrl,c")
        custom_keys: Comma-separated list of keys to press together for "custom" action.
        
    Returns:
        str: Status message confirmation.
    """
    try:
        if shortcut == "settings":
            await asyncio.to_thread(pyautogui.hotkey, 'win', 'i')
            return "✅ विंडोज सेटिंग्स खोली गई हैं। (Win + I)"
            
        elif shortcut == "task_view":
            await asyncio.to_thread(pyautogui.hotkey, 'win', 'tab')
            return "✅ टास्क व्यू खोला गया है। (Win + Tab)"
            
        elif shortcut == "action_center":
            await asyncio.to_thread(pyautogui.hotkey, 'win', 'a')
            return "✅ एक्शन सेंटर खोला गया है। (Win + A)"
            
        elif shortcut == "lock_pc":
            import ctypes
            try:
                await asyncio.to_thread(ctypes.windll.user32.LockWorkStation)
                return "✅ सिस्टम लॉक किया गया है।"
            except:
                await asyncio.to_thread(pyautogui.hotkey, 'win', 'l')
                return "✅ सिस्टम लॉक किया गया है। (Win + L)"
                
        elif shortcut == "custom":
            if not custom_keys:
                return "❌ कृपया 'custom_keys' (उदा. 'ctrl,alt,delete') प्रदान करें।"
            keys = [k.strip() for k in custom_keys.split(",")]
            await asyncio.to_thread(pyautogui.hotkey, *keys)
            return f"✅ शॉर्टकट '{custom_keys}' सफलतापूर्वक निष्पादित किया गया।"
            
    except Exception as e:
        return f"❌ शॉर्टकट निष्पादन में त्रुटि: {str(e)}"
    return "❌ अज्ञात शॉर्टकट एक्शन।"
